name: CI
on:
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: java/maven:3.6.3-ibmjava-8
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
